name: Deploy to ECR

on: 
  push:
    branches: [ master ]

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1
   
 
    - name: MYSQL docker run and pushed to ecr repo
      run: |
        # Docker build
        docker build . --file Dockerfile_mysql --tag v0.1 
        docker ps
        docker tag my_sql:latest 374997061608.dkr.ecr.us-east-1.amazonaws.com/my_sql:latest && docker push 374997061608.dkr.ecr.us-east-1.amazonaws.com/my_sql:latest
